### ISSUE TITLE
Use MoveIt .scene file instead of custom yaml file to persist a planning scene

### ISSUE THREAD

**Issue by jarkenau** [DFKI-NI/grasplan#24]
MoveIt provides a `.scene` format to persist and load planning scenes. Replacing our custom `yaml` format to this format would allow easier integration of external planning scenes. The example below shows the structure of the file format for storing a box:

```
* table_1
13.22 2.15 0.36
0 0 0.707107 0.707107
1
box
1.4 0.7 0.72
0 0 0
0 0 0 1
0 0 0 0
0
```

instead of 

```yaml
- scene_name: 'table_1'
  frame_id: 'map'
  box_x_dimension: 1.40
  box_y_dimension: 0.70
  box_z_dimension: 0.72
  box_position_x: 13.22
  box_position_y: 2.15
  box_position_z: 0.36
  box_orientation_x: 0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.7071
  box_orientation_w: 0.7071
```

Further there is also a node that can publish the scene from the `.scene` file https://github.com/ros-planning/moveit/blob/master/moveit_ros/planning/planning_components_tools/src/publish_scene_from_text.cpp, so that we don't have to parse and publish it (as it is currently done with the `yaml` files).
